In [1]:
# Kimberly Tai - DS4200 Final Project Code
import pandas as pd
import matplotlib.pyplot as plt
import altair as alt

In [2]:
ev = pd.read_csv("Electric_Vehicle_Population_Data.csv")
ev.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5UXTA6C0XM,Kitsap,Seabeck,WA,98380.0,2021,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30.0,0.0,35.0,267929112,POINT (-122.8728334 47.5798304),PUGET SOUND ENERGY INC,5.303509e+10
1,5YJ3E1EB1J,Kitsap,Poulsbo,WA,98370.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,23.0,475911439,POINT (-122.6368884 47.7469547),PUGET SOUND ENERGY INC,5.303509e+10
2,WP0AD2A73G,Snohomish,Bothell,WA,98012.0,2016,PORSCHE,PANAMERA,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,15.0,0.0,1.0,101971278,POINT (-122.206146 47.839957),PUGET SOUND ENERGY INC,5.306105e+10
3,5YJ3E1EB5J,Kitsap,Bremerton,WA,98310.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,23.0,474363746,POINT (-122.6231895 47.5930874),PUGET SOUND ENERGY INC,5.303508e+10
4,1N4AZ1CP3K,King,Redmond,WA,98052.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,0.0,45.0,476346482,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [3]:
makes = ev.groupby(['Make', 'Model']).size()
makes = pd.DataFrame(makes).reset_index()

In [4]:
makes.columns = ['make', 'model', 'count']
makes

                     make   model  count
0                   ACURA     ZDX     61
1              ALFA ROMEO  TONALE     84
2                    AUDI      A3    567
3                    AUDI    A7 E     11
4                    AUDI    A8 E      3
..                    ...     ...    ...
148                 VOLVO     V60     79
149                 VOLVO    XC40   1171
150                 VOLVO    XC60   1371
151                 VOLVO    XC90   1766
152  WHEEGO ELECTRIC CARS  WHEEGO      3

[153 rows x 3 columns]

In [5]:
make_list = list(makes.make.unique())

In [6]:
# A dropdown filter
make_dropdown = alt.binding_select(options=make_list, name="Make: ")
make_select = alt.selection_point(fields=['make'], bind=make_dropdown)

In [7]:
base = alt.Chart(makes).mark_bar().encode(
    x=alt.X('model:N'),
    y=alt.Y('count:Q'),
    tooltip=['make:N', 'model:N', 'count:Q']
).properties(
    width=900
)

In [8]:
filter_make = base.add_params(
    make_select
).transform_filter(
    make_select
).properties(title="Make and Model Counts")

In [9]:
filter_make

alt.Chart(...)

In [10]:
#filter_make.save("interactive_makemodel.html")

In [11]:
top_ten = pd.DataFrame(ev.groupby(["Make"]).size()).reset_index()

In [12]:
top_ten.sort_values(0, inplace=True, ascending=False)
top_ten.head(10)

          Make      0
36       TESLA  91379
7    CHEVROLET  15419
28      NISSAN  14721
12        FORD  11138
19         KIA   9576
5          BMW   8607
38      TOYOTA   8248
16     HYUNDAI   6068
32      RIVIAN   5883
40  VOLKSWAGEN   5783

In [13]:
top_ten_makes = top_ten.head(10).Make
list(top_ten_makes)

['TESLA',
 'CHEVROLET',
 'NISSAN',
 'FORD',
 'KIA',
 'BMW',
 'TOYOTA',
 'HYUNDAI',
 'RIVIAN',
 'VOLKSWAGEN']

In [14]:
years = ev.groupby(['Model Year', 'Make']).size()
years = pd.DataFrame(years).reset_index()
years.columns = ['year', 'make', 'count']

years.head()

   year    make  count
0  1999    FORD      2
1  2000    FORD      7
2  2002  TOYOTA      2
3  2003  TOYOTA      1
4  2008   TESLA     22

In [15]:
top_ten_years = years[years['make'].isin(list(top_ten_makes))]
top_ten_years

     year     make  count
0    1999     FORD      2
1    2000     FORD      7
2    2002   TOYOTA      2
3    2003   TOYOTA      1
4    2008    TESLA     22
..    ...      ...    ...
260  2025      BMW    205
263  2025  HYUNDAI     30
264  2025      KIA     58
268  2025   NISSAN     59
270  2025   RIVIAN    199

[120 rows x 3 columns]

In [16]:
base = alt.Chart(years).mark_bar().encode(
    x=alt.X("make:N"),
    y=alt.Y("count:Q"),
    tooltip=["make", "count"]
).properties(title="EVs per Model Year")

In [17]:
# A slider filter
year_slider = alt.binding_range(min=1999, max=2025, step=1, name="Year: ")
slider_selection = alt.selection_point(bind=year_slider, fields=['year'])

filter_year = base.add_params(
    slider_selection
).transform_filter(
    slider_selection
)

In [18]:
filter_year
#filter_year.save("interactive_yearmake.html")

alt.Chart(...)